baseURL = 'https://anastasiiamorozova.github.io/website/'
languageCode = 'en-us'
title = 'anastasiiamorozova'
publishDir = 'docs'


[module]
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

[params]
title = "I'm Anastasiia Morozova"
author = "Anastasiia Morozova"
description = "always up for a new challenge\n\nChallenge-driven and a natural team player with a strong interest in combining OSINT and data analysis to uncover stories. I get the most satisfaction from taking a unique idea all the way from pitch through brainstorming, reporting, writing, designing, and editing. Co-authored award-winning investigative pieces.\n\nHere are a few examples of my data work. I use <strong>Python</strong> to explore and extract data, design visualizations in <strong>Illustrator</strong>, and create maps with <strong>Mapbox</strong> and <strong>QGIS</strong>. For interactive projects, I work with <strong>JavaScript</strong> and <strong>Svelte</strong>.\n\n<strong>nst.morozova13@gmail.com</strong>"
profilePicture = "images/profile.jpeg"
contentratio = 0.7
hidesidebar = false
disableTitleCapitalization = true
relativeURLs = false
customCss = ["/css/custom.css"]


[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/nst-morozova/"

[menu]

  [[menu.main]]
  name = "My stories"
  identifier = "stories"
  weight = 100
  url = "https://anastasiiamorozova.github.io/portfolio/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "https://anastasiiamorozova.github.io/website/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

